# Generated by Django 4.1.4 on 2023-02-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=120)),
                ('lprice', models.IntegerField()),
                ('lcreateddate', models.DateTimeField(auto_now=True)),
                ('lis_published', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'library',
            },
        ),
    ]
